### ISSUE TITLE
Restrict concurrent builds for all sub-projects?

### ISSUE THREAD

**Issue by toupeira** [mjdetullio/multi-branch-project-plugin#101]
I saw there's an option "Execute concurrent builds if necessary" which seems to apply only for each sub-project, meaning different branches of the same project will still be built concurrently if this option is disabled. Is there a way to avoid this, basically the same flag on the parent project?

My use case is: I want to have more than one executor and different parent projects building concurrently, but only build one branch per parent project concurrently (because of DB and port conflicts).

And while I'm here I want to thank you for all your work with this plugin, it really made Jenkins a lot more powerful for us!

**Comment by mjdetullio** [comment]
Try the throttle concurrent builds plugin and configure the parent project
with a category, which will be synced to each subproject.  Set the limit
for the category to 1 or 1 per node.

**Comment by toupeira** [comment]
Thanks for the tip! I tried that out but didn't like that I have to add a new category for each project, so I settled on the [Build Blocker](https://wiki.jenkins-ci.org/display/JENKINS/Build+Blocker+Plugin) plugin instead which at least has the setting right there in the project, and it seems to work fine with the multi-branch plugin.
