### ISSUE TITLE
Cannot add the post build step of the Findbugs Plugin

### ISSUE THREAD

**Issue by balta3** [mjdetullio/multi-branch-project-plugin#106]
I'm creating a Multibranch Maven project and have the [FindBugs plugin](https://wiki.jenkins-ci.org/display/JENKINS/FindBugs+Plugin) installed. Sadly the post build step of the plugin is not available when configuring the multibranch project. Is this a problem of this plugin or should I report it to the author of the FindBugs plugin?

**Comment by mjdetullio** [comment]
The FindBugs and other Static Analysis plugins aren't configured under "Post-build Actions".  Instead, they are found under "Build Settings", just above it.  Behavior is the same for both Maven projects and Maven multi-branch projects.
