### ISSUE TITLE
Template config is cleared when server runs out of disk-space and job is updated

### ISSUE THREAD

**Issue by guscatalano** [mjdetullio/multi-branch-project-plugin#108]
I ran into a situation where the server ran out of space and my jobs lost their build steps because in a multi-branch job under template\config.xml it got saved to 0 bytes. There must be a bug somewhere in the code that doesn't gracefully handle situations like this.

**Comment by mjdetullio** [comment]
All configs are saved using the Jenkins core APIs and aren't necessarily the fault of this plugin.  Generally when you run out of disk there are all sorts of erratic behaviors.  I would recommend putting your Jenkins configuration on a separate volume to prevent this from happening in the future.
