### ISSUE TITLE
Build Other Projects support

### ISSUE THREAD

**Issue by marcellodesales** [mjdetullio/multi-branch-project-plugin#110]
Hi there,

How can I relate different projects? Considering I have the Jobs A (master, develop) and B (master, develop), where A must trigger a build on B. I'd like to trigger per branch:

* Branch A (`$BRANCH_NAME`) ------triggers------> Branch B (`$BRANCH_NAME`)

That way, I can verify that any changes in a given branch is aligned with the the dependencies of that branch.

**Comment by mjdetullio** [comment]
It appears this is not possible to do with either the "Build other projects" or "Trigger parameterized build on other projects" __post-build__ actions.  However, it _is_ possible to do it with the "Trigger/call builds on other projects" __build step__.

You'll need two plugins: Environment Injector Plugin and Parameterized Trigger plugin.

Assuming you have two multi-branch projects, for example ```multibranch-build``` and ```multibranch-test```, that both have the same SCM config, where you want a branch build to trigger a branch test:

Configure ```multibranch-build``` with:

1. EnvInject evaluated Groovy script: ```return [BRANCH_ENCODED: currentJob.name]``` (or add that entry to your existing returned map)
2. Build step "Trigger/call builds on other projects" with the job name ```multibranch-test/${BRANCH_ENCODED}```

**Comment by mjdetullio** [comment]
And actually I'd suggest using the Workflow Plugin w/ Multibranch Workflow to accomplish this type of task, rather than using separate jobs.

**Comment by marcellodesales** [comment]
@mjdetullio Thanks for the info... I will verify this on my setup!
