### ISSUE TITLE
Clone Project is NOT cloning ALL the fields from the `Cloned item`

### ISSUE THREAD

**Issue by marcellodesales** [mjdetullio/multi-branch-project-plugin#111]
Attempting to create a new Job with the option `Copy existing Item -> Clone from`, the only field cloned is the `Git Project Repository`...

All of the other fields are empty... I had most of the fields filled out here in the original project.

<img width="1064" alt="screen shot 2015-10-16 at 11 53 36 am" src="https://cloud.githubusercontent.com/assets/131457/10550573/93f37772-73fc-11e5-84c4-0828cea8d1ef.png">

thanks
Marcello

**Comment by nschloe** [comment]
Bumped into this as well.

**Comment by marcellodesales** [comment]
@nschloe Yeah, a bummer, but this plugin rocks!!!

**Comment by marcellodesales** [comment]
@a-wheeler Can you please describe the step-by-step of your hack? I'm quite not familiar with it...

**Comment by a-wheeler** [comment]
This requires Java 7+.
1) Get the scriptler plugin. (Or use a system groovy build job). https://wiki.jenkins-ci.org/display/JENKINS/Scriptler+Plugin
2) Add a new scriptler script.
3) Add two parameters 'source_job' and 'destination_job'.
4) Paste in the above groovy script.
5) Run script on your master specifying the job to copy and the name of the new job.

**Comment by marcellodesales** [comment]
@a-wheeler Thank you... I will try it ASAP...

**Comment by mjdetullio** [comment]
Closing in favor of #44
