### ISSUE TITLE
Git: synchronize tags as well

### ISSUE THREAD

**Issue by theimdal** [mjdetullio/multi-branch-project-plugin#121]
Hi.

Today I'm able to automatically synchronize all branches by combining Gitlab "web hooks" with the gitlab-hook-plugin, and your plugin. So every branch change triggers Jenkins to create multi-branch-jobs and start building the affected branch. And this works brilliantly.

However,  I would also like to synchronize tags, so Jenkins can build the tag for me. I already have a Gitlab web hook in place, that should be picked up by the gitlab-hook-plugin, but according to the gitlab-hook-plugin you need to configure the git SCM branch specifier to "'refs/tags/${TAGNAME}'".

I think I have seen somewhere that you for some logical reason have removed the branch specifier option from the SCM part? And even if it is available, I'm not sure that it would work anyway.

But maybe you can add an option somewhere, to allow tag synchronization as well as branches?

I can help with development/testing if needed! :-)

**Comment by mjdetullio** [comment]
I _think_ this would be implemented in the Git Plugin.  In the SCM API, there is no differentiation between tags and branches (they're just "heads").  So, the Git Plugin must only be retrieving branches.
