### ISSUE TITLE
Configuration Option: Check out to specific local branch (needed for M2 Release Plugin)

### ISSUE THREAD

**Issue by ThomasReinhardt** [mjdetullio/multi-branch-project-plugin#123]
For maven releases we use the M2 Release Plugin (https://wiki.jenkins-ci.org/display/JENKINS/M2+Release+Plugin). This can not work if there is no local branch (in fact it seems the local branch has to have the same name as the origin).
The GIT option in Jenkins is "Check out to specific local branch", but of course this has to be different for every branch. Maybe we can use $GIT_BRANCH for this.

**Comment by mjdetullio** [comment]
See #47.
