### ISSUE TITLE
wrong id for table row in dashbard view

### ISSUE THREAD

**Issue by fantastory** [mjdetullio/multi-branch-project-plugin#124]
When showing branch jobs on jenkins dashboard, they generate single
<tr id="job_$(BRANCH)"> for every branch.
Now having two repositories with same branches each:
front:
  develop
  release
  master

backend:
  develop
  release
  master

we get <tr id="job_master"> twice, which is not allowed in html
It better be 
<tr id="job_backend_master"> and 
<tr id="job_front_master">

**Comment by mjdetullio** [comment]
The Dashboard view plugin would have to add support for a nested item hierarchy.
