### ISSUE TITLE
SSH auth not supported?

### ISSUE THREAD

**Issue by somedamnthing** [mjdetullio/multi-branch-project-plugin#125]
Using Github Enterprise as my code repository, I'm able to create a normal git-based job using '-none-' credentials (jenkins user, default ~/.ssh key) for an SSH based URL and have it work fine. Using the multi-branch plugin, SSH auth does not work, but HTTPS absolutely does.

Is SSH not a supported authentication method for this plugin?

**Comment by mjdetullio** [comment]
SSH is supported as far as I know.  Make sure the key is on the master.  Try a few different key protocols.  Make sure host keys are accepted.

Regardless, if it's a bug then it's with the Git Plugin, not this one.  In the future use the Jenkins users mailing list for troubleshooting.

**Comment by somedamnthing** [comment]
This works perfectly with the Git Plugin; as stated, I'm able to create a normal git-based job using '-none-', but the multi-branch plugin does not have this capability.

**Comment by mjdetullio** [comment]
The Git Plugin provides the SCM functionality for this plugin
