### ISSUE TITLE
Folder icon is blue but the folder contains a failed job

### ISSUE THREAD

**Issue by DavidA2014** [mjdetullio/multi-branch-project-plugin#131]
Since upgrading from Jenkins 1.639 to 1.642, my multi-branch projects are now represented by folder icons instead of the usual ball. One of these multi-branch folders contains a failed job, indicated by a red ball, but the folder icon is blue. So, from the dashboard, I can't identify all failed jobs. 

I am running Multi-Branch Project Plugin 0.4.1.

I have raised this as an issue on the Jenkins Jira:

https://issues.jenkins-ci.org/browse/JENKINS-32056

but was advised to raise an issue here also.

**Comment by mjdetullio** [comment]
Check the bottom of the configuration page for the icon setting and change
it to ball color

**Comment by DavidA2014** [comment]
Where exactly is that setting please?

**Comment by mjdetullio** [comment]
On the multi branch job

**Comment by DavidA2014** [comment]
Thanks for your help.
