### ISSUE TITLE
Creating multi-branch jobs via REST API?

### ISSUE THREAD

**Issue by jordemort** [mjdetullio/multi-branch-project-plugin#18]
Is there a way to specify the builders for multi-branch projects when creating them via the API?

We're migrating a bunch of our builds over to the multi-branch plugin and we've hit a bit of a snag. We have a script that creates jobs for us by writing out a new config.xml based on a template and then posts that to createItem. However, it appears that for multi-branch jobs, the builders and such aren't actually stored in config.xml; they end up in templates/config.xml. I tried starting with a multi-branch project's config.xml and merging the builders and other stuff from templates/config.xml, and posting that, but it did not work; I end up with a multi-branch project with no builders (the same thing happens whey I try and copy a multi-branch project in the Jenkins UI)

What I'm hoping for is a way to pass the builders along in what I post to createItem, although I'd settle for being able to add them in via the API after the job is created. Otherwise, I'm either going to have to rewrite config.xml behind Jenkins' back or sniff what the job creation form is POSTing and emulate that, neither of which sound like a lot of fun.

**Comment by mjdetullio** [comment]
After some refactoring with version 0.2 there aren't any checks in place to prevent direct configuration on the template.  You'll still have to modify the configuration after creation but you should now be able to do it via POST to ```${JOB_URL}/template/config.xml```.

**Comment by lucagiove** [comment]
Would be nice to have this working with standard api like python-jenkins, maybe having a sub section of the standard configuration xml that includes the template?
I guess this is the reason why also the copy from an existent job doesn't copy all the settings.
