### ISSUE TITLE
Trigger by SNAPSHOT builds

### ISSUE THREAD

**Issue by pwhittlesea** [mjdetullio/multi-branch-project-plugin#19]
In Maven jobs, you can trigger by SNAPSHOT dependencies and trigger jobs downstream which depend on the built artefact.

Am I correct in coming to the conclusion that this plugin does not support this behaviour?

**Comment by mjdetullio** [comment]
I did attempt to implement a Maven-style multi-branch project but there are some limitations with the APIs.  I still have the code for it floating around but it would depend on me making a contribution to the Maven Project Plugin and possibly Jenkins core.
