### ISSUE TITLE
promotions configuration are not saved

### ISSUE THREAD

**Issue by pirulino** [mjdetullio/multi-branch-project-plugin#21]
Hi,
using the multi-branch pluging the promotions configuration are not saved. 
Steps to reproduce it:
1) open the configuration page
2) select "Promote builds when..." option and fill the form with some data
3) save
4) re-open the configuration page: the option is deselected and the previous data are lost

is this a known bug? 

Jenkins used version: 1.579

Thanks for the help

**Comment by mjdetullio** [comment]
Probably fixed with the refactoring in 0.2.  I can reopen if it's still an issue.
