### ISSUE TITLE
Support "Use custom workspace" option

### ISSUE THREAD

**Issue by gb96** [mjdetullio/multi-branch-project-plugin#22]
Freestyle job has an "Advanced Project Options" section including "Use custom workspace". This allows a custom workspace directory path to be used instead of the default unique workspace.

With Multi-Branch Project Plugin job, the default workspace is currently "workspace/ProjectName/branchName" which makes some sense, allowing each branch to be checked out into a separate directory.

However there are many use cases where a custom workspace directory is required, for example:

1. JENKINS_HOME is on a disk partition that is slow or low on free space, or for whatever reason the developer wants their project workspace in a different disk partition (e.g. a Ram disk or SSD for build-speed, a network share).
2. Single Version Control Repository contains multiple projects or sub-projects, located in sub-directories (e.g. git@bitbucket.org:myTeam/myProjectRepo.git/myProject1/ ). In this case a git checkout of a branch will include all projects in the repo.  In the default workspace config, if you have N sub-projects, each job will checkout all N sub-projects resulting in N^2 * (number branches) projects checked out. For jenkins job efficiency in this scenario it is best for all jobs for the sub-projects within myProjectRepo.git to share a common workspace, e.g. ws/myProjectRepo/$BRANCH_NAME. This will result in each project only being checked out once per branch.
3. Inter-project dependencies implemented by relative path references in the filesystem. Commonly in developer IDE multiple inter-dependent projects can reference eachother's content by simple relative path references when they are located within a common workspace directory (e.g. workspace1/project1/include/hello.h can contain a reference #include "../project2/include/world.h" where both project1 and project2 reside within common parent directory workspace1.  This relationship is still maintained by default within Jenkins Freestyle build jobs since the job workspaces will still be siblings (workspace/project1 and workspace/project2). However with Multi-Branch Project Plugin, these workspaces are pushed down a level (workspace/project1/$BRANCH_NAME and workspace/project2/$BRANCH_NAME) so the relative reference to ../project2/include/world.h is now broken in Jenkins.  A quick-fix for this kind of problem could be to change the current default workspace to "workspace/$BRANCH_NAME/projectName", however a custom workspace option would address more scenarios.

**Comment by mjdetullio** [comment]
Now available with version 0.2

**Comment by gb96** [comment]
Awesome,  thanks for implementing this!
