### ISSUE TITLE
When deleting a branch build initially fails, then branches sync

### ISSUE THREAD

**Issue by czalidis** [mjdetullio/multi-branch-project-plugin#25]
I am using this plugin for github repositories. When I am deleting a branch on the remote end (github), a build is triggered that fails because it can not find the particular branch (as is has been deleted). Then when the branches get synced, the deleted branch is removed properly.

Shouldn't the delete event trigger the branch removal instead of triggering a build?

This is might happening due to misconfiguration by me, so I apologise in advance if that is the case.

**Comment by mjdetullio** [comment]
Currently there is no mechanism for this plugin to parse the GitHub hook data and trigger a removal rather than a build.
