### ISSUE TITLE
Add file include and exclude patterns for triggers

### ISSUE THREAD

**Issue by DoCode** [mjdetullio/multi-branch-project-plugin#26]
Like this one from [git-plugin](https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/extensions/impl/PathRestriction.java)

**Comment by mjdetullio** [comment]
While it may be part of the core SCM implementation in the Git Plugin, it is also up to them to implement it for their implementation of the SCMSource API.  All SCM settings for this plugin are drawn from the other plugins.
