### ISSUE TITLE
jgit error: authentication not supported

### ISSUE THREAD

**Issue by jon-p** [mjdetullio/multi-branch-project-plugin#29]
Our git server uses http authentication (username and password) and jgit doesn't seem to support that. Although from what I can tell from http://www.codeaffine.com/2014/12/09/jgit-authentication/ and  https://bugs.eclipse.org/bugs/show_bug.cgi?id=296201 it does?  

This is the error message:

FATAL: org.eclipse.jgit.api.errors.TransportException: https://gitrepo: authentication not supported

**Comment by mjdetullio** [comment]
This plugin uses APIs provided from other plugins such as the SCM API Plugin and Git Plugin.  I recommend you do some more troubleshooting or direct your issue to the Git Plugin.
