### ISSUE TITLE
multi-branch and multi-scm support

### ISSUE THREAD

**Issue by lianghu** [mjdetullio/multi-branch-project-plugin#35]
Would it possible to co-work with this plugin?

https://github.com/jenkinsci/multiple-scms-plugin

We have a project with multiple git repos, and all repos have same branches.

It would be great to use the plugin to support multi branch on the multi-repo project.

**Comment by mjdetullio** [comment]
The APIs between these two plugins are very incompatible.  If anything, the implementation for this feature request would go in that project.
