### ISSUE TITLE
new branches creation

### ISSUE THREAD

**Issue by vernyquartara** [mjdetullio/multi-branch-project-plugin#38]
The very good thing with this plugin is that you can have all your branches clearly visible in just one place and customize the view.

The plugin should be improved by adding a feature for create new branches, as [SVN Merge plugin](https://wiki.jenkins-ci.org/display/JENKINS/Subversion+Merge+Plugin) can do.

**Comment by mjdetullio** [comment]
Sorry to say that's far outside the scope of this plugin (in my mind at least).

The point is to allow SCM branch listings to automatically control Jenkins jobs, not the other way around.
