### ISSUE TITLE
Not possible to specify shadow branches at SCM

### ISSUE THREAD

**Issue by scaytrase** [mjdetullio/multi-branch-project-plugin#43]
I've started to use your multibranch plugin for feature branch testing. Currently, PR shadow branches should be tested the same way as usual heads. Basic Git SCM allows to specify refspec i.e like following

Remote name: `origin`
Refspec: `+refs/*:refs/remotes/origin/*`
Branch specifier: `:.*pull-requests/.*/merge`

And PR shadow branch will be used.

Currently even `*` branch specification sees only `master` and `production` branches (so, all the general `ref/heads/*` branches).

**Comment by walkamongus** [comment]
I'd also like PRs to be included. Im currently having to use a separate job to watch for PRs and it would be awesome to be able to do both in a single job.

**Comment by mjdetullio** [comment]
SCM options, including those on the multi-branch project configuration page, are implemented by the SCM plugins themselves.

**Comment by scaytrase** [comment]
Well, but SCM on the multibranch projects differs with one on the freeconfig project. 

![MB SCM Config](https://cloud.githubusercontent.com/assets/6578413/8423974/1f1ee702-1efb-11e5-9623-2831787a7309.png)

vs.

![Freestyle SCM Config](https://cloud.githubusercontent.com/assets/6578413/8423968/f3e237f6-1efa-11e5-9f24-94cba7dce2d9.png)

**Comment by scaytrase** [comment]
If we have the save grade config for multibranch config - that would be nice. at least to solve this issue 
`Branches to build` and `Refspec` fields should replace given `include branches` and `exclude branches` options

**Comment by mjdetullio** [comment]
Sure, they look different, but this plugin still uses APIs that are provided by other plugins.  There is no code in this plugin for any SCM configuration settings.

**Comment by scaytrase** [comment]
Yeah, I look through the sources and see that. Thank you for clarifying, I'll try to do something with it
