### ISSUE TITLE
Advanced Git behaviour not supported?

### ISSUE THREAD

**Issue by gmetal** [mjdetullio/multi-branch-project-plugin#47]
It appears that the advanced behaviour when using Git, is not supported. For example, an advanced Git behaviour that is not supported is initialising and syncing  submodules. Are there any plans to implement this?

**Comment by rmasters** [comment]
I ran into this today. I want to do shallow clones but the button for "Advanced behaviour" doesn't exist under the Git-SCM options. It doesn't appear on the Multi-Branch config page, but it does appear on the individual branch configure pages. Not much help to me as I want new branches to do shallow clones by default but this might help people who want to change existing branches.

**Comment by mjdetullio** [comment]
SCM options, including those on the multi-branch project configuration page, are implemented by the SCM plugins themselves.
