### ISSUE TITLE
Deadlock in AbstractMultiBranchProject class

### ISSUE THREAD

**Issue by montgomery1944** [mjdetullio/multi-branch-project-plugin#48]
Jstack output available at https://gist.github.com/montgomery1944/690b8d71321d7d9f576f.

It seems that the problem is caused because getSubProjects method is synchronized. To be honest, I haven't found why is this method synchronized. Is it because of the lazy initialization?

I use MultiBranch Project plugin version 0.2.2.

**Comment by mjdetullio** [comment]
The lazy instantiation is one reason but it's primarily because the cron task that updates the branch projects runs the risk of modifying the collection while it is being iterated.

**Comment by boucher** [comment]
Just wanted to let you know I'm experiencing the same deadlock, really frequently. 
Log: https://gist.github.com/boucher/3d6624ad76f3cbffb5c2

**Comment by jtjeferreira** [comment]
same here
