### ISSUE TITLE
Issue on Scripting (Jenkins getItemByFullName API with slashes)

### ISSUE THREAD

**Issue by vijithrapidvalue** [mjdetullio/multi-branch-project-plugin#50]
i am trying to take the build history using scripting using this code 
```javascript
import jenkins.model.Jenkins
import hudson.model.AbstractProject
import hudson.model.Result
import hudson.util.RunList
AbstractProject<?, ?> otherJob = Jenkins.getInstance().getItemByFullName("ProjectName", AbstractProject.class)
RunList<?> builds = otherJob.getBuilds().overThresholdOnly(Result.SUCCESS)
return builds.limit(50).collect { it.number }
```
But in this code only taking the trunk project only. did't get the result of branch projects 
please help me....

**Comment by mjdetullio** [comment]
```getItemByFullName``` uses the slash as a separator token, making the assumption that between each slash is an item.  Jenkins does declare the slash as unsafe if I were to try creating a job through the UI, but it also doesn't allow characters needed for name encoding.

For this API to work properly I'd have to work on the option to replace branch slashes and other characters with an underscore or other user configurable character per #15 

Try using another API like getAllItems

```
Jenkins.getInstance().getAllItems(AbstractProject.class).find { it.getFullName() == "project/branches/example" }
```

**Comment by scaytrase** [comment]
Yes, implementing #15 looks the most plausible way to solve this
