### ISSUE TITLE
Bubble build status up to host project view

### ISSUE THREAD

**Issue by twaddington** [mjdetullio/multi-branch-project-plugin#54]
This is a great plugin. I have my branches building and everything's working great so far. It looks like the multiproject has "Last Success" and "Last Failure" listed as "N/A" for the main project view. It would be great if it pulled the last success and last failure up from the built branches. Not sure how difficult this would be to do. Thoughts?

**Comment by twaddington** [comment]
### Job
![screen shot 2015-05-08 at 7 21 49 pm](https://cloud.githubusercontent.com/assets/107117/7548286/80bad06a-f5b7-11e4-8cf5-b9e5e4f97d0f.png)
### Branches
![screen shot 2015-05-08 at 7 21 04 pm](https://cloud.githubusercontent.com/assets/107117/7548279/6589c242-f5b7-11e4-82ff-84847dc0a9b0.png)

**Comment by jtjeferreira** [comment]
+1

**Comment by smazurov** [comment]
agreed, maybe add inheritance order with a few options: 
1. set `[branchname]` as "overall" build status
2. set last run as overall for success and failure, attach branch to build name. (i.e it would say **1minute 2 seconds [branchname - #3](/)**. Last duration would be latest's build duration, with branch in parenthesis. 

Also, same can be said about the "weather" icon. Its always sunny, even if branches themselves got clouds and rain

**Comment by mjdetullio** [comment]
Added with version 0.3
