### ISSUE TITLE
Cannot rename or clone a multibranch project

### ISSUE THREAD

**Issue by twaddington** [mjdetullio/multi-branch-project-plugin#55]
Would be really useful to be able to rename a project. It doesn't look like it's possible to clone a multibranch project to a new name either. This failed for me.

Ref https://github.com/mjdetullio/multi-branch-project-plugin/issues/44

**Comment by harniman** [comment]
Clone appeared to work, but, the Build steps were missing

**Comment by moshezvi** [comment]
+1 on the missing build steps

**Comment by scaytrase** [comment]
#44 Has working workaround, btw.

**Comment by mjdetullio** [comment]
Closing in favor of #44
