### ISSUE TITLE
Some of the branch projects are automatically disabled

### ISSUE THREAD

**Issue by moshezvi** [mjdetullio/multi-branch-project-plugin#59]
I've noticed this on two separate projects:
The plugin creates several branch projects (e.g. master, testing, testing-iter-XX).
The 'master' branch project is created enabled, but at a certain point (definitely on Jenkins restart, possibly also during branch recalculation), it is disabled.

**Comment by mjdetullio** [comment]
It is possible to disable individual branch projects and the parent will track it.

If you can provide some detailed step-by-step instructions for me to reproduce I'll look into it.
