### ISSUE TITLE
Jenkins GUI gets incredibly slow after adding a multibranch project

### ISSUE THREAD

**Issue by gv2011** [mjdetullio/multi-branch-project-plugin#61]
Jenkins: 1.607 deployed on Tomcat 7, using jdk1.8.0_45 on Ubuntu 14.10
Multi-Branch-Project Plugin 0.2.2

I have two normal Maven projects, one very simple and one huge.
The plugin works fine for the small one.
When I enter the configuration data for a new multibranch project and press "Save", Jenkins doesn't respond to the save request and gets very slow (or doesn't respond at all) on other browser windows.

After a restart of Tomcat, Jenkins works again. The multibranch project complains it cannot find any branches and says I should configure GIT. When I open the configuration page of the project, everything looks fine (GIT is configured), but when I press Save, Jenkins doesn't respond again.

The main difference between the working and the not-working project is probably that the latter has more than 100 branches.

**Comment by mjdetullio** [comment]
100 branches is huge.  When you hit "Save" the plugin is configured to sync the branches and sub-projects and unfortunately my laziness in implementation makes this happen on the same thread.

If you wait it out, the Sync Branches cron should happen as a flyweight task in the background.

**Comment by gv2011** [comment]
Hi Matthew,

I had another problem of executing it on the same thread: The rights are
those of the logged in user, which in my case had not been sufficient to
delete the files of a sub-project that was removed during sync.

I play around with a fork currently - maybe I can contribute something
at a later point in time. There seem to be some multithreading issues
when dealing with a big amount of branches.

Best, Eberhard

Am 30.06.15 KW26 um 03:46 schrieb Matthew DeTullio:
