### ISSUE TITLE
Mercurial version list is empty, no branches found

### ISSUE THREAD

**Issue by utapyngo** [mjdetullio/multi-branch-project-plugin#66]
When I configure a multibranch mercurial project, the list of mercurial versions is empty:
![selection_072](https://cloud.githubusercontent.com/assets/1124655/8074917/0acb1d60-0f52-11e5-9e46-d7de1bf270d8.png)

In no-multi-branch projects the list of version is not empty:
![selection_074](https://cloud.githubusercontent.com/assets/1124655/8074944/7796cec6-0f52-11e5-9ad2-1a1567c61220.png)

I hoped it would work without specifying the version but the all view shows this:
![selection_071](https://cloud.githubusercontent.com/assets/1124655/8074918/0acc84ac-0f52-11e5-9732-fc0a68e1331e.png)

I am using latest versions of Multi-Branch Project and Mercurial plugins:
![selection_075](https://cloud.githubusercontent.com/assets/1124655/8074985/5647a5fa-0f53-11e5-9475-8f67f8b84be7.png)

**Comment by mjdetullio** [comment]
SCM options, including those on the multi-branch project configuration page, are implemented by the SCM plugins themselves.

**Comment by utapyngo** [comment]
Do you have any idea why the list differs for multibranch project and for simple project?

**Comment by mjdetullio** [comment]
It's an implementation detail for the Mercurial plugin.  Not sure why without looking at the source.
