### ISSUE TITLE
Git branches containing / not pollable

### ISSUE THREAD

**Issue by holger-s** [mjdetullio/multi-branch-project-plugin#67]
Hi,

i have the following issue: I have feature branches that follow the feature/bugfix/hotfix pattern e.g.

feature/bling-bling
bufgix/fix-something

when the multibranch plugin creates subjects for these the same branch names show up in the "branches to build". 
The git plugin polling mechanism does not detect these branches. The branch should be fully qualified to be detected, e.g. "origin/feature/bling-bling". 
This works for branches without / in the name, because the Jenkins git plugin adds wildcards to branches  if they do not contain slashes. A branch named "fix-something" would be resolved as "*/fix-something". 

However, a branch named "feature/bling-bling" will be resolved as "feature/bling-bling" and will not be work (it should be "origin/feature/bling-bling").

I would suggest a solution but would like to get your input before I submit a PR: 
Instead of specifying the plain branch name in "branches to build", specify the fully qualified branch name, including "origin/".

What do you think?

(There is an issue in the git plugin related to this, https://issues.jenkins-ci.org/browse/JENKINS-27332, and they will probably fix it, but IMO it is unwise to rely on these mysterious inner workings)

Regards,
Holger

**Comment by jsrois** [comment]
@holger-s  I've found the same issue you pointed out. In my case, a branch `release/0.1` is detected (a new job is created), but polling doesn't work for that branch in particular. If I create a new "standard" (not multibranch) job for any ( * ) branch, the polling works with all branches including release/XX ; so I guess it's not a git-plugin issue. 
Did you finally solve the problem? I'd like to keep using the multibranch plugin, but I can't do it with this issue ... :/

**Comment by holger-s** [comment]
we introduced a new rule, that strips the "/" out of the branches:
feature/new-stuff => f-new-stuff

very specific, but worked :)

**Comment by jsrois** [comment]
Hehe I guess fixing the human part is a valid workaround. Thanks! :)
