### ISSUE TITLE
jenkins freeze when the sync happen when the specific branch already running

### ISSUE THREAD

**Issue by morlajb** [mjdetullio/multi-branch-project-plugin#70]
Hi

we started use this plugin several days ago. sometimes Jenkins just stuck and we had to restart the Master ( Ubuntu 14.04) . I did a lot of testing and find out that  when the sync runs at the same time when the specific branch is running. it just freeze.

BTW , I think it will be great to add timestamp for the branch log
Syncing configuration to project for branch feature-AAA
Syncing configuration to project for branch feature-BBB
Syncing configuration to project for branch feature-CCC
Syncing configuration to project for branch feature-DDD
Syncing configuration to project for branch feature-EEE
Syncing configuration to project for branch feature-FFF

so it will be easier to understand 

I will be happy to send you any more info to fix this one.

Thanks , Mor

**Comment by morlajb** [comment]
I just open a bug with the log file of the master 
https://issues.jenkins-ci.org/browse/JENKINS-29124?filter=-2

**Comment by morlajb** [comment]
Hi

I am using the latest code , and it looks much better - the plugin works fine.
I saw that sometimes the sync takes 2 seconds ( we have ~ 40 branches ) and sometimes it takes ~ 30 seconds.  i think it will be great to have timestamp to the sync log - it will help to find the reason.

BTW , when are you planning to release a new version of the plugin ?

**Comment by mjdetullio** [comment]
New version released
