### ISSUE TITLE
Branch workspaces are not removed when the branch is deleted

### ISSUE THREAD

**Issue by le6o** [mjdetullio/multi-branch-project-plugin#72]
It seems when branches are removed the workspace is left behind.

**Comment by mjdetullio** [comment]
Duplicate

**Comment by le6o** [comment]
Sorry, I did look for a similar issue but couldn't find one.

https://github.com/mjdetullio/multi-branch-project-plugin/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+workspace

 Where is the duplicate so I can subscribe to updates?

**Comment by mjdetullio** [comment]
#52 #32
