### ISSUE TITLE
Branches with slashes causing broken links in conjunction with other plugins

### ISSUE THREAD

**Issue by IvanAnishchuk** [mjdetullio/multi-branch-project-plugin#76]
It's probably not exactly caused by multibranch plugin but definitely related and maybe can be worked around in some fashion. When branch name contains slashes everything depends on that encoding and when it's for some reason gets decoded, Jenkins cannot find the url. It often happens with plugins like Cobertura and Sloccount and their links from the project page.

It happens like this: link from project page leads to `{plugin}` (like `cobertura/`) (which is `/job/{jobname}/{branchname}/{plugin}`) which gets redirected to `{lastbuildnumber}/{plugin}` which is usually ok but URI-encoded symbols in the `{branchname}` get force-decoded and jenkins returns 404 error.

It can be worked around if we can avoid relying on URI encoding somehow which is actually very fragile thing (proxy servers, browsers, and jenkins itself can do stuff with it).

Following are links to external bug reports to plugin developers and maybe we should also submit a report to core developers (so it stops forcing the decoding).

https://issues.jenkins-ci.org/browse/JENKINS-29351
https://github.com/jenkinsci/cobertura-plugin/issues/44

**Comment by mjdetullio** [comment]
Should be fixed in 0.4
