### ISSUE TITLE
Build status not reported in cc.xml

### ISSUE THREAD

**Issue by eMerzh** [mjdetullio/multi-branch-project-plugin#81]
I've installed and configured the plugin...

it works well but i have a few issues : 
It doesn't report the builds to the cc.xml file ( http://myjenkins/cc.xml  ).
unfortunately this file is used by some tool to integrate into jenkins ...

(it could also be great if the main project included some details from branch view like last build date, ...)

**Comment by mjdetullio** [comment]
You can get reports for the branch view from a URL such as http://localhost:8080/jenkins/job/freestyle-multi/view/All/cc.xml

But the feature is part of core.  As you can see there's generally no support for nested items.  You could probably submit a relatively simple pull request to core.

https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/model/View/cc.xml.jelly
