### ISSUE TITLE
Unable to set Additional Behaviours for a git project

### ISSUE THREAD

**Issue by bdrust** [mjdetullio/multi-branch-project-plugin#82]
There isn't a way to set any Additional Behaviours at the parent project level that would apply to all brannches.  When I attempt to remove the "Strategy for choosing what to build" and add "Wipe out repository & force clone" for an individual branch, It saves but then after a bit it reverts back to the original value.

**Comment by pioto** [comment]
:+1:

**Comment by acaire** [comment]
:+1:

**Comment by wadahiro** [comment]
@bdrust @acaire it's outside the scope of this plugin. It is Git plugin specific. So [I sent pull request to Git plugin](https://github.com/jenkinsci/git-plugin/pull/350). If this pr is merged, you can use 'Additional Behaviours' option. 
In addition, it allows you to use 'Repository Browser' option which is mentioned in the #97.

**Comment by acaire** [comment]
Appreciate it, thanks!
