### ISSUE TITLE
Sync Branches is not working

### ISSUE THREAD

**Issue by sjgroomi** [mjdetullio/multi-branch-project-plugin#85]
On OSX Jenkins v 1.624 & 1.623, automatic branch syncing doesn't seem to be working.

With * * * * * (every minute) set as the "Sync Branches Schedule", the branches are synced upon saving the configuration but never again.

If you can let me know where I may find any further relevant logs or information I will update the ticket and provide them

**Comment by glefloch** [comment]
I'm running the same issue... can you please fix it

**Comment by scaytrase** [comment]
@mjdetullio Same here. Branches were not syncing for about a month. Restarting jenkins help to trigger sync once, but repeated sync does not occures

**Comment by mjdetullio** [comment]
Found out this was from the same thing as the jelly exception on the sync branches log.  This requires a significant amount of effort to fix.

It works properly in another branch I've pushed up ```abstractitem```, but there are some major API changes, support for project-based matrix authorization is lost, and I haven't quite finished testing.

If you're feeling up to it you can build that branch yourself but be wary it will do some config migration on the parent project and there's no return path.

But don't worry, I'm hacking away on it

**Comment by stephen-sage** [comment]
@mjdetullio What is "project-based matrix authorization?".  Is it guaranteed that the API will remain the same as `abstractitem` going forward or is this just an experimental branch that could be thrown away eventually?

Thanks

**Comment by mjdetullio** [comment]
It's one of the auth strategies that allows you to configure permissions for a project on the project itself.  I believe some people are using it because there was a bug related to it a long time ago.  I'm waiting on a PR for it.

```abstractitem``` will likely be the new API unless I encounter a show stopper while testing it.  Right now it appears to be fairly stable, and I also want to test out the experimental maven multi-branch project with it because that will be turned on eventually.

**Comment by tvollstaedt** [comment]
+1

**Comment by isleshocky77** [comment]
Jenkins 1.624
multi-branch-project-plugin 0.2.4

Using the same method as @tvollstaedt to refresh the branches every once in a while as a work-around for now.

**Comment by acqant** [comment]
+1

**Comment by shehzan10** [comment]
Is downgrading to 0.2.3 a work around?

**Comment by mjdetullio** [comment]
Fixed with version 0.3

**Comment by isleshocky77** [comment]
Works for me with the update.  Thanks for the fix.
