### ISSUE TITLE
JellyTagException when trying to configure the project...

### ISSUE THREAD

**Issue by ihadanny** [mjdetullio/multi-branch-project-plugin#87]
Using Jenkins 1.570
Multi-branch version 0.2.4

Upon first access to configure screen, getting this: 

javax.servlet.ServletException: org.apache.commons.jelly.JellyTagException: jar:file:/civolume/ARSBIGDATA-5696/jenkins/plugins/multi-branch-project-plugin/WEB-INF/lib/classes.jar!/com/github/mjdetullio/jenkins/plugins/multibranch/FreeStyleMultiBranchProject/configure-branch-entries.jelly:60:31: <j:getStatic> Could not access hudson.model.JDK.DEFAULT_NAME.  Original exception message: DEFAULT_NAME
	at org.kohsuke.stapler.jelly.JellyFacet$1.dispatch(JellyFacet.java:103)

**Comment by mjdetullio** [comment]
Should be fixed with version 0.3
