### ISSUE TITLE
Support Maven Projects

### ISSUE THREAD

**Issue by pioto** [mjdetullio/multi-branch-project-plugin#89]
A feature request, though I don't know how hard it would be to implement:

It'd be nice to have a project type that's a cross between this plugin and the standard Maven plugin. For Maven-based projects, that plugin provides easier, more powerful integration with Jenkins than the current Freestyle projects supported by this plugin currently.

**Comment by mjdetullio** [comment]
Has been dormant for awhile but now released with version 0.3
