### ISSUE TITLE
Branch Project configurations getting cleared

### ISSUE THREAD

**Issue by tterrag1098** [mjdetullio/multi-branch-project-plugin#91]
I'm not sure if this is intentional, but it seems that every time the branches are synced, I lose all custom configurations in the branch projects. For instance I have set up my dev branch to build nightly, but that is erased every sync back to the defaults (no nightlies).

**Comment by mjdetullio** [comment]
This is intended.  Older versions of this plugin used to hide the configuration option of the branch projects, but there were some drawbacks to the structure of that implementation and wasn't able to find a way to hide the option in newer versions.

**Comment by tterrag1098** [comment]
Perhaps the sub-projects could maintain a list of what config options have been edited, then overwrite every config option except those. It doesn't sound hard but I don't know much about the jenkins API (famous last words I know ;))
