### ISSUE TITLE
Trunk builds fine, yet branches followed by a slash fails 

### ISSUE THREAD

**Issue by zverbatim** [mjdetullio/multi-branch-project-plugin#92]
I've set up the plugin for the _trunk_ and a _branch/6_.
The _trunk_ builds fine using grails 2.2.4 yet the _branch/6_ fails.

Please tell if the encoding of the slash following _branches_ causes  the issue that later dependencies are not resolved.
i.e. `branches/6` is encoded to `branches%2F6/`

**Note**:
- i always check a fresh copy from the svn
- i do a `grails` clean and `grails compile --refresh-dependencies`

Snipped from the jenkins console output for the branch/6 build:
```
|Environment set to development
......    [mkdir] Created dir: /opt/jenkins/home/jobs/xyz-multibranch/branches/branches%2F6/workspace/target/projects/xyz/plugin-classes
.Error 
|
Fatal error during compilation org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/opt/jenkins/home/jobs/xyz-multibranch/branches/branches%2F6/workspace/target/projects/xyz/plugins/jaxrs-0.9/./JaxrsGrailsPlugin.groovy: 4: unable to resolve class org.grails.jaxrs.generator.CodeGenerator
 @ line 4, column 1.
   import org.grails.jaxrs.generator.CodeGenerator
   ^
```

**Comment by mjdetullio** [comment]
Alternative encoding schemes that use safer characters are being researched, but a failed compilation due to a % in the filesystem in the path is an edge case bug in your tooling and not this plugin.
